### ISSUE TITLE
How to use the application

### ISSUE THREAD

**Issue by AMI231187** [jsastriawan/mc2router#3]
Hi,

I'm am new to this application, acn you help how to install and configure the same,

**Comment by jsastriawan** [comment]
Here are simplified step assuming that you know what you are doing:
1. First of all, you need to install nodejs and node-webkit. See: https://nodejs.org/en/ and https://nwjs.io/
2. Clone or download zip of this repository and unpack it.
3. Go to the folder where it is extracted and install run: npm install
4. Create a file called config.json as described in the repository.
5. To run the application, run: nw

A newer version of this application written using ElectronJS is https://github.com/jsastriawan/mc2router-electron
The step is almost like what I have written above, the only difference is that you will need to install ElectronJS instead of NWJS and the way to run it is using command: electron .

I hope this helps.
